app:
  name: toolsForBiology

spring:
  messages:
    encoding: UTF-8
  security:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/pascalbardeau?useUnicode=true&characterEncoding=utf-8
    username: pascalbardeau
    password:
    driver-class-name: org.postgresql.Driver
    initialize: true
    minimumIdle: 3
    maximumPoolSize: 5
    validationQuery: SELECT 1
    initialSize: 1
    maxActive: 3
    testWhileIdle: true
    testOnBorrow: true
    sqlScriptEncoding: UTF-8
  jpa:
    database: POSTGRESQL
    show-sql: true
    format_sql: true
    generate-ddl: true
    hibernate.ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_schema: public
        flushMode: AUTO
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        connection:
          charSet: UTF-8
server:
  port: 9000
  contextPath:

logging:
  level:
    org.springframework.web: ERROR
    com.toolsforbiology: DEBUG
    org.hibernate.SQL: ERROR
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %X{mdcData}%5p [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} - %X{mdcData} %5p - %msg%n"


jwt:
  header: Authorization
  expires_in: 1800 #30 minutes
  change:
    password:
      expires_in: 3600
  refresh:
    expires_in: 28800
  secret: 3AfnKZR2ltF4


message.login.disabled: "Votre compte est verrouillé. Veuillez prendre contact avec le référent de votre entité pour déverrouiller ce dernier."
message.login.email: "L'adresse e-mail n'existe pas"
message.login.password: "Le mot de passe est incorrect"
message.login.password.reinit: "Vous devez réinitialiser votre mot de passe."
message.login.blocage.temporel: "Vous avez atteint le nombre maximal de tentatives. Votre compte est bloqué pendant 1h, veuillez attendre ce délai pour vous authentifier de nouveau."
AbstractUserDetailsAuthenticationProvider.disabled: "Votre compte est verrouillé. Veuillez prendre contact avec le référent de votre entité pour déverrouiller ce dernier."
AbstractUserDetailsAuthenticationProvider.locked: "Votre compte est verrouillé. Veuillez prendre contact avec le référent de votre entité pour déverrouiller ce dernier."

security:
  ignored:
  - "*.bundle.*"